name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  runs-on: ubuntu-latest
  name: A job to say hello
  steps:
  - name: Hello world action step
    id: hello
    uses: Appendino/hello-world-docker-action
    with:
      who-to-greet: 'eu mesmo'
  - name: Get the output time
    run: echo "The time was ${{ steps.hello.outputs.time }}"
